add styled component CounterStyled
isdi-coders-202207-bcn-coding-adventure/adrian-arco-front pull request #3
Opened 2022-08-22 14:02 UTC by AdrianArcoGonzalez

2022-08-22 14:06 UTC, luisdudamel requested changes

2022-08-22 14:06 UTC, luisdudamel commented on src/components/Counter/Counter.Styled.ts
> +  & .list-item {
Hola Adrián,
El ampersand lo utilizamos para concatenar clases.
Aquí no tiene mucho sentido.

2022-08-22 14:17 UTC, AdrianArcoGonzalez commented on src/components/Counter/Counter.Styled.ts
> +  & .list-item {
revisado y cambiado la letra, gracias!

2022-08-22 14:30 UTC, luisdudamel approved these changes

2022-08-22 14:31 UTC, luisdudamel commented
Dale la funcionalidad. Guarda la fecha clave en una constante que puedas usar en cualquier componente.

2022-08-22 14:32 UTC, merged

2022-08-24 17:45 UTC, mariogl commented
@AdrianArcoGonzalez el contador tiene que estar en el centro del viewport, tanto en vertical como en horizontal.

2022-08-24 18:09 UTC, AdrianArcoGonzalez commented
ok! lo repaso, gracias!


El mié, 24 ago 2022 a las 19:45, mariogl ***@***.***>)
escribió:

> @AdrianArcoGonzalez <https://github.com/AdrianArcoGonzalez> el contador
> tiene que estar en el centro del viewport, tanto en vertical como en
> horizontal.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/isdi-coders-202207-bcn-coding-adventure/adrian-arco-front/pull/3#issuecomment-1226043715>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWLESBJMQCOGNHO4Q7UQRLDV2ZNUZANCNFSM57HZVA7A>
> .
> You are receiving this because you were mentioned.Message ID:
> <isdi-coders-202207-bcn-coding-adventure/adrian-arco-front/pull/3/c1226043715
> @github.com>
>