add countdown timer functionality
isdi-coders-202207-bcn-coding-adventure/adrian-arco-front pull request #4
Opened 2022-08-23 14:22 UTC by AdrianArcoGonzalez

2022-08-23 14:38 UTC, NachoLosada requested changes
@AdrianArcoGonzalez Recuerda lo que dijo Mario. Tenemos que trabajar todo con FECHAS ;)

2022-08-23 17:28 UTC, AdrianArcoGonzalez commented
Okeey lo reviso!

2022-08-24 11:10 UTC, NachoLosada approved these changes

2022-08-24 11:11 UTC, NachoLosada commented
Te lo apruebo pero recuerda echarle un ojo al buguito del initialState ;)

2022-08-24 11:12 UTC, AdrianArcoGonzalez commented
okii le pego un ojo, gracias!

2022-08-24 11:12 UTC, merged

2022-08-24 11:13 UTC, mariogl commented on src/utils/dateCountDown.ts
> +const finalDate = new Date("2022-08-26").getTime() / 1000;
Si este archivo tiene una sola variable y la exporta, se debería llamar igual que la variable.

2022-08-24 11:13 UTC, AdrianArcoGonzalez commented on src/utils/dateCountDown.ts
> +const finalDate = new Date("2022-08-26").getTime() / 1000;
lo cambio ahora mismo, gracias!

2022-08-24 11:17 UTC, mariogl commented
Fase 5. Testea el componente contador.

2022-08-24 11:17 UTC, AdrianArcoGonzalez commented
Gracias

2022-08-24 15:21 UTC, dawgun commented on src/components/Counter/Counter.tsx
> +    let timeLeft = finalDate - new Date().getTime() / 1000;
Esto debería ser una variable const, ya que no se re-asigna más tarde.

2022-08-24 15:21 UTC, dawgun commented on src/index.css
> +  background-color: #243342;
Este color esta muy feo, pero para gustos colores.

2022-08-24 15:45 UTC, AdrianArcoGonzalez commented on src/components/Counter/Counter.tsx
> +    let timeLeft = finalDate - new Date().getTime() / 1000;
Gracias! Ahora lo repaso. Gracias!